#!/bin/sh
umask 0022
set -u    
unset IFS 
export LC_ALL='C'
export PATH="$(command -p getconf PATH)${PATH:+:}:${PATH:-}:$(pwd)/wbin"
bndr=$(mime-make -m)
cat skeleton/template/POST
mime-make -b "$bndr" -F DATA $1 -T PATH $2
