#!/bin/sh
set -u
umask 0022
unset IFS
export LC_ALL='C'
LF=$(printf '\\\012_')
LF=${LF%_}
TITLE=$(if [ $1 != "-" ]; then  cat $1 | head -n 1 | sed 's/^# / /' ; fi)
CDESC=$(if [ $1 != "-" ]; then  cat $1 | awk '/^# /,/^!--$/' | grep -v '^# '|grep -v '^!--$' ; fi)

while getopts t:u: OPT
do
  case $OPT in
    t) XUSER="$OPTARG"
       ;;
    u) XHOST="$OPTARG"
       ;;
  esac
done
shift $(($OPTIND - 1))

cat <<END
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1.0">
<title>${TITLE}</title>
<meta name="description" content="${CDESC}">
<meta property="og:type" content="article">
<meta name="twitter:card" content="summary" />
<meta name="twitter:site" content="${XUSER:-none}" />
<meta property="og:url" content="${XHOST:-none}/${1#*/}" />
<meta property="og:title" content="${TITLE}" />
<meta property="og:description" content="${CDESC}" />
<meta property="og:image" content="https://${XHOST:-none}/.attachments/img/image.png" /> 
<meta property="og:site_name" content="${XHOST:-none}" />
<meta property="og:locale" content="ja_JP" />

<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/.attachments/img/site-tile-150x150.png">
<meta name="theme-color" content="#f5deb3">
<link rel="icon" type="image/x-icon" href="/.attachments/img/favicon.ico">
<link rel="apple-touch-icon" sizes="180x180" href="/.attachments/img/apple-touch-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192" href="/.attachments/img/android-chrome-192x192.png">
<link rel="shortcut icon" type="image/svg+xml" sizes="any" href="/.attachments/img/icon.svg" />
<link rel="manifest" href="/.attachments/img/manifest.json">

<link rel="stylesheet" href="/.attachments/css/markdown.css">
<link rel="stylesheet" href="/.attachments/css/prism.css">
<script src="/.attachments/js/prism.js"></script>
<script src="/.attachments/js/stub.js"></script>
<script src="/.attachments/js/comments.js"></script>
<script src="/.attachments/js/mokuji.js"></script> 
</head>
<body>
<header>
<ul class="breadcrumb" style="margin-bottom: 0 !important;">
$(printf "%s\n" $1 |
awk -F '/' '{
  for(i=1; i <NF+1; i++) {
    for (j=1; j <i+1; j++) {
      printf("%s/", $j); 
    }
    printf("\n");
  } 
}' | sed '$d' |
awk -v RD=${1%%/*} '{
  printf("<li itemscope=\042itemscope\042 itemtype=\042http://data-vocabulary.org/Breadcrumb\042>\n");
  cmdline=sprintf("sed \047s:%s::\047",RD);
  printf("<a href=\042%s\042 itemprop=\042url\042>\n", $0) | cmdline ;
  close(cmdline);
  print $0;
  printf("</a>\n");
  printf("</li>\n");
  }'|
awk -F '/' '/\/$/{ printf("<span itemprop=\042%s\042>%s</span>\n", $(NF-1), $(NF-1));}/^</')
</ul>
</header>
<section>
<article id="contents">
END
cat ${1} |
sed 's/\&/\&amp;/g' | sed s'/\(.\)>/\1\&gt;/g' | sed 's/</\&lt;/g' |
awk '{
  if( ! blockflag && /^>/){
    print("<blockquote>");
    blockflag = 1;
  } else
  if( blockflag && !/^>/ ){
    $0 = "</blockquote>\n"$0;
    blockflag = 0;
  }
  gsub(/^>/, "");
  print $0
}' |
awk 'BEGIN{ code=0; }{
  if($0 ~ /^```.*$/) { code=1; }
  if($0 ~ /^```$/) { code=0; }
  if( ! code && ! lflag && /^[*-+] /){
    print("<ul>");
    lflag = 1;
  } else 
  if( ! code && lflag && !/^[*-+] / && /^$/){
    $0 = "</ul>\n"$0;
    lflag = 0;
  }
  if( ! nflag && /^[0-9]\. /){
    print("<ol>");
    nflag = 1;
  } else
  if( ! code && nflag && !/^[0-9]\. / && /^$/){
    $0 = "</ol>\n"$0;
    nflag = 0;
  }
  print $0
}'|
awk 'BEGIN{ code=0; }{
     if($0 ~ /^```.*$/) { code=1; }
     if($0 ~ /^```$/) { code=0; }
     if($0 !~ /^[*-+] / && $0 !~ /^[0-9]\. /) { print $0}
     if(/^[*-+] /) {
        if(!code) {
          print "<li>" substr($0, 3) "</li>";
          next;
        } else {
          print $0;
        }
     }
     if(/^[0-9]\. /) {
        if(!code) {
          print "<li>" substr($0, 3) "</li>";
          next;
        } else {
          print $0;
        }
     }
}' |
grep -v '^!--$'    |
sed 's@^!toc$@<div class="toc" id="toc"></div>@' |
awk '$0 !~ /^$/ && $0 !~ /^(#|##|###|####|#####) / && $0 !~ /^\|/{
       cmdline="sed \"s:  $:<\\/br>:g\" |tr \"\n\" \" \""; 
       end = 0;
       list = 0;
       if ($0 ~ /^```.*$/) {
         flag = 1;
       }
       if ($0 ~ /^```$/) {
         flag = 0;
         end = 1;
       }
       if (!flag) {
	 if (!end)
           print $0 | cmdline; close(cmdline)
       }
     }
     /^$/ { if(!flag){ if(!end) printf("\n\n") }}
     /^(#|##|###|####|#####) /{print $0}
     $0 ~ /^```.*$/,/^```$/
     /^\|/ && $0 !~ /\t---/
     END{printf("\n");}' |
sed 's/ \(##*\) /'"${LF}"'\1 /' |
awk '$0 !~ /^$/ && $0 !~ /^(#|##|###|####|#####) / && $0 !~ /^- / && $0 !~ /^\* / && $0 !~ /^1\. / && $0 !~ /\|/ {
       end = 0;
       if ($0 ~ /^```.*$/) {
	       flag = 1;
       }
       if ($0 ~ /^```$/) {
	       flag = 0;
               end = 1;
       }
       if (!flag) {
	 if (!end)
		 printf("<p>%s</p>\n",$0);
       }
     }
     /^(#|##|###|####|#####) /{print $0}
     $0 ~ /^```.*$/,/^```$/
     $0 ~ /^\|/,/^\|/' |
awk -F \| '/^\|/ && $0 !~ /\|---/{printf("<tr>"); for(i=2; i<NF; i++) {printf("<td>%s</th>", $i);} printf("</tr>");} $0 !~ /^\|/' |
sed 's/\(<\/tr>\)\(<[^t][^r]\)/\1'"$LF"'\2/' |
sed 's/^\(<tr.*<\/tr>\)$/<table>\1<\/table>/' |
sed 's/^# \(.*\)/<section>'"$LF"'<h1>\1<\/h1>/' |
sed 's/^## \(.*\)/<\/section>'"$LF"'<section>'"$LF"'<h2>\1<\/h2>/' |
sed 's/^### \(.*\)/<\/section>'"$LF"'<section>'"$LF"'<h3>\1<\/h3>/' |
sed 's/^#### \(.*\)/<\/section>'"$LF"'<section>'"$LF"'<h4>\1<\/h4>/' |
sed 's/^##### \(.*\)/<\/section>'"$LF"'<section>'"$LF"'<h5>\1<\/h5>/' |
sed 's/```\(..*\)/<pre><code class="language-\1">/' |
sed 's/^```$/<\/code><\/pre>/' |
sed 's/`\([^`]*\)`/<code>\1<\/code>/g' |
sed 's/<p>!\[\(.*\)\](\(.*\)) <\/p>/<p><a target="_blank" rel="noopener noreferrer" href="\2"><img src="\2" alt="\1" style="max-width:100%;"><\/a><\/p>/' |
sed 's/\(<\/br>\)/'"$LF"'\1'"$LF"'/g' |
sed 's/\[\([^\[]*\)\](\([^(]*\))/<a target="_blank" rel="noopener noreferrer" href="\2">\1<\/a>/g' |
sed 's/\*\*\([^\*]*\)\*\*/<strong>\1<\/strong>/g' |
#sed 's/::\([^:]*\)::/<mark>\1<\/mark>/g' |
cat ;

FILENEME="$(echo ${1##*/} | sed 's/.*/.comments-&/')"
FILEPATH="$(echo ${1%/*} | sed 's/exo//')/"
if [ -f "${1%%/*}${FILEPATH}${FILENEME}" ]
then
cat <<END
</section>
</article>
</section>
<footer>
<button class="scroll-top" id="js-button">^</button>
<script>scrollTop('js-button', 500);</script>
<hr/>
<hr/>
<!--
<form action="${FILEPATH}${FILENEME}" method="POST" enctype="multipart/form-data" accept-charset="UTF-8" onsubmit="AJAXSubmit(this, '${FILEPATH}${FILENEME}'); return false;">
<dl>
<dt>Name</dt>
<dd><input type="text" name="USRNAME" value="" /></dd>
<dt>Comment</dt>
<dd><textarea name='DATA"; filename="${FILENEME}' cols="50" rows="5" ></textarea></dd>
</dl>
<input type="hidden" name="PATH" value="${FILEPATH}" />
<input type="submit" name="post" value="add comment" />
</form>-->
<iframe width="100%" height="10" id="stub" frameborder="no"></iframe>
<script>
window.onload = function () {
  var link = '${FILEPATH}${FILENEME}';
  stub(link);
  setTimeout(resize, 2000)
};
</script>
<form action="${FILEPATH}${FILENEME}" method="POST" enctype="multipart/form-data" accept-charset="UTF-8" onsubmit="AJAXSubmit(this, '${FILEPATH}${FILENEME}'); return false;">
<dl>
<dt>Name</dt>
<dd><input type="text" name="USRNAME" value="" /></dd>
<dt>Comment</dt>
<dd><textarea name='DATA"; filename="${FILENEME}' cols="50" rows="5" style="width: 100%;"></textarea></dd>
</dl>
<input type="hidden" name="PATH" value="${FILEPATH}" />
<input type="submit" name="post" value="add comment" />
</form>
</footer>
<hr/>
<hr/>
</body>
</html>
END
else
cat<<END
</section>
</article>
</section>
<footer>
<hr/>
<hr/>
</footer>
</body>
</html>
END
fi
